pipeline {
    agent any

    stages {
        stage('Backend Unit Test') {

            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
