pipeline {
    agent any

    stages {
        agent {
            docker {
                image 'snakee/golang-junit:1.21'
                reuseNode true
            }
        }

        stage('Backend Unit Test') {
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
